version: "3"
services:
  ethereum:
    image: rwthacis/monitored-geth-client
    ports:
      - 30303:30303/udp
      - 30303:30303/tcp
      - 8545:8545/tcp
      - 8546:8546/tcp
    environment:
      GETH_VERBOSITY: "3"
      ETHEREUM_DATA_DIR: /root/.ethereum/devchain
    volumes:
      - ethereumStoragePersistent:/root/.ethereum/devchain
    command: /root/start.sh
  las2peer:
    image: rwthacis/las2peer
    ports:
      - 8080:8080
      - 9080:9080/tcp
      - 9080:9080/udp
    environment:
      LAS2PEER_ETH_HOST: ethereum:8545
      LAS2PEER_PORT: 9080
    depends_on:
      - ethereum
  hye:
    build: .
    ports:
      - 9081:9081/tcp
      - 9081:9081/udp
    environment:
      LAS2PEER_ETH_HOST: ethereum:8545
      LAS2PEER_PORT: 9081
      BOOTSTRAP: las2peer:9080
      SLEEP_FOR: 90
volumes:
  ethereumStoragePersistent: {}
